name: Build web app on Github gh pages

on:
  push:
    branches: [main]

jobs:
  build-web:
    name: Build web app on Github gh pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Flutter ğŸ”§
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Build app âš™ï¸
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /toy-health/
